<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products=[
            [
                'product_name' => 'Beauty Blender',
                'slug' => 'beautry-blender',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'1',
                'size'=>'XL',
                'material'=>'Milk',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'beautyblenderProduct.png',
            ],
            [
                'product_name' => 'Body Oil',
                'slug' => 'baby-oil',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1100',
                'color'=>'red',
                'category_id'=>'1',
                'size'=>'XL',
                'material'=>'oil',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'bodyOilProduct.png',
            ],
            [
                'product_name' => 'Eyelash Curler',
                'slug' => 'eyelash-curler',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1200',
                'color'=>'red',
                'category_id'=>'1',
                'size'=>'XL',
                'material'=>'aluminium',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'eyeLashCurlerProduct.png',
            ],
            [
                'product_name' => 'Hair Brush',
                'slug' => 'hair-brush',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1300',
                'color'=>'red',
                'category_id'=>'1',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'hairbrushProduct.png',
            ],
            [
                'product_name' => 'Lipstick',
                'slug' => 'lipstick',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1400',
                'color'=>'red',
                'category_id'=>'1',
                'size'=>'XL',
                'material'=>'wax',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'Lipstick.png',
            ],
            [
                'product_name' => 'Mascara',
                'slug' => 'mascara',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1600',
                'color'=>'red',
                'category_id'=>'1',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'mascaraProduct.png',
            ],
            [
                'product_name' => 'Perfume',
                'slug' => 'perfume',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1700',
                'color'=>'red',
                'category_id'=>'1',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'perfumeProduct.png',
            ],
            [
                'product_name' => 'Kite Runner',
                'slug' => 'kite-runner',
                'description' => '"The Kite Runner" is a novel by Khaled Hosseini about Amir, a boy from Kabul, Afghanistan.',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'7',
                'size'=>'XL',
                'material'=>'paper',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'kiterunnerProduct.png',
            ],
            [
                'product_name' => 'Notebook',
                'slug' => 'notebook',
                'description' => 'These notebooks are crafted with high-quality paper and durable covers, ensuring a premium writing experience that lasts.',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'7',
                'size'=>'XL',
                'material'=>'paper',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'notebookProduct.png',
            ],
            [
                'product_name' => 'Painting Color',
                'slug' => 'panting-color',
                'description' => 'High-quality art materials for artists of all levels, providing everything needed to unleash your creativity.',
                'price'=>'900',
                'color'=>'red',
                'category_id'=>'7',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'paintingColorProduct.png',
            ],
            [
                'product_name' => 'Pilot pen',
                'slug' => 'pilot-pen',
                'description' => 'Pilot pens offer a superior writing experience, combining precision engineering with innovative design for diverse needs.',
                'price'=>'80',
                'color'=>'red',
                'category_id'=>'7',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'pilotpenProduct.png',
            ],
            [
                'product_name' => 'Sketching Marker',
                'slug' => 'sketching-marker',
                'description' => 'Sketching markers offer vibrant, blendable ink to bring their creations to life effortlessly.',
                'price'=>'1300',
                'color'=>'red',
                'category_id'=>'7',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'sketchingMarkerProduct.png',
            ],
            [
                'product_name' => 'Airpods',
                'slug' => 'airpods',
                'description' => 'Airbuds offer convenient, immersive wireless audio, ideal for music lovers and those on the go.',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'2',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'Apple',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'airpodsProduct.png',
            ],
            [
                'product_name' => 'Canon Camera',
                'slug' => 'canon-camera',
                'description' => 'Canon cameras are known for superior image quality and reliability to capture lifes moments creatively.',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'2',
                'size'=>'XL',
                'material'=>'metal',
                'brand'=> 'canon',
                'weight'=>'1',
                'warranty'=>'5',
                'merchant_id'=>'3',
                'images'=>'CanonProduct.png',
            ],
            [
                'product_name' => 'Headphone',
                'slug' => 'headphone',
                'description' => 'Headphones provide immersive audio, comfort, and style, enhancing your music, gaming, or podcasting experience.',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'2',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'Apple',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'headphoneProduct.png',
            ],
            [
                'product_name' => 'Iphone11 Charger',
                'slug' => 'iphone11-charger',
                'description' => 'iPhone chargers offer fast and reliable power delivery, keeping your device charged at home, in the office, or on the go.',
                'price'=>'1100',
                'color'=>'red',
                'category_id'=>'2',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'Apple',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'iphone11ChargerProduct.png',
            ],
            [
                'product_name' => 'Mac Book Pro M2',
                'slug' => 'mac-book-pro-m2',
                'description' => 'MacBooks offer a seamless blend of performance, portability, and innovative features for creative professionals and everyday users.',
                'price'=>'50000',
                'color'=>'red',
                'category_id'=>'2',
                'size'=>'XL',
                'material'=>'metal',
                'brand'=> 'Apple',
                'weight'=>'2',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'macBookProM2Product.png',
            ],
            [
                'product_name' => 'Power bank',
                'slug' => 'power-bank',
                'description' => 'Power banks provide portable charging for smartphones and USB devices, ensuring you stay connected on the go.',
                'price'=>'1400',
                'color'=>'red',
                'category_id'=>'2',
                'size'=>'XL',
                'material'=>'metal',
                'brand'=> 'Samsung',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'powerbankProduct.png',
            ],
            [
                'product_name' => 'Jacket',
                'slug' => 'jacket',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1200',
                'color'=>'red',
                'category_id'=>'3',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'jacket.png',
            ],
            [
                'product_name' => 'Pant',
                'slug' => 'pant',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'3',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'pantProduct.png',
            ],
            [
                'product_name' => 'Sari',
                'slug' => 'sari',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'2000',
                'color'=>'red',
                'category_id'=>'3',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'sariProduct.png',
            ],
            [
                'product_name' => 'Sweater',
                'slug' => 'sweater',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'3000',
                'color'=>'red',
                'category_id'=>'3',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'sweater.png',
            ],
            [
                'product_name' => 'Tshirt',
                'slug' => 'tshirt',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'500',
                'color'=>'red',
                'category_id'=>'3',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'tshirtProduct.png',
            ],
            [
                'product_name' => 'Coffee',
                'slug' => 'coffee',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'4',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'coffeeProduct.png',
            ],
            [
                'product_name' => 'Corn Flakes',
                'slug' => 'con-flakes',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'4',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'cornFlakesProduct.png',
            ],
            [
                'product_name' => 'Egg',
                'slug' => 'egg',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'450',
                'color'=>'red',
                'category_id'=>'4',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'eggProduct.png',
            ],
            [
                'product_name' => 'Juice',
                'slug' => 'juice',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'100',
                'color'=>'red',
                'category_id'=>'4',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'juiceProduct.png',
            ],
            [
                'product_name' => 'Milk',
                'slug' => 'milk',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'120',
                'color'=>'red',
                'category_id'=>'4',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'milkProduct.png',
            ],
            [
                'product_name' => 'Sausage',
                'slug' => 'sausage',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'320',
                'color'=>'red',
                'category_id'=>'4',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'sausageProduct.png',
            ],
            [
                'product_name' => 'Bookcase',
                'slug' => 'bookcase',
                'description' => 'This stylish bookcase offers adjustable shelves and ample storage, enhancing any room`s elegance.',
                'price'=>'320',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'metal',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'bookcaseProduct.png',
            ],
            [
                'product_name' => 'Chair',
                'slug' => 'chair',
                'description' => 'This chair offers modern design and ergonomic support, perfect for work or relaxation.',
                'price'=>'1400',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'wooden',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'chair.png',
            ],
            [
                'product_name' => 'Clock',
                'slug' => 'clock',
                'description' => 'Classic style clock, mechanical or electrical device for displaying time.',
                'price'=>'850',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'clockProduct.png',
            ],
            [
                'product_name' => 'Couch',
                'slug' => 'couch',
                'description' => 'This stylish couch offers plush comfort, creating a cozy centerpiece for any living space.',
                'price'=>'3200',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'couchProduct.png',
            ],
            [
                'product_name' => 'Knife',
                'slug' => 'knife',
                'description' => 'This sleek knife is crafted for precision and durability, ideal for any kitchen or outdoor adventure.',
                'price'=>'150',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'Steel',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'Knife.png',
            ],
            [
                'product_name' => 'Badminton',
                'slug' => 'badminton',
                'description' => 'The shuttlecock for fast rallies and precise shots, ensuring an exciting game for all skill levels.',
                'price'=>'550',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'badmintonProduct.png',
            ],
            [
                'product_name' => 'Basketball',
                'slug' => 'basketball',
                'description' => 'Designed for durability and optimal bounce, ideal for both practice sessions and intense games.',
                'price'=>'800',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'rubber',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'basketballProduct.png',
            ],
            [
                'product_name' => 'Boxing Gloves',
                'slug' => 'boxing-gloves',
                'description' => 'These durable boxing gloves offer high-quality materials for long-lasting performance and protection.',
                'price'=>'5500',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'leather',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'boxingGlovesProduct.png',
            ],
            [
                'product_name' => 'Dumbell',
                'slug' => 'dumbell',
                'description' => 'Dumbbells are short bars with weights on each end, used for strength training and muscle toning.',
                'price'=>'1400',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'metal',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'dumbellProduct.png',
            ],
            [
                'product_name' => 'Football',
                'slug' => 'football',
                'description' => 'This football is crafted for durability and optimal performance, ideal for practice sessions and intense games.',
                'price'=>'700',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'leather',
                'brand'=> 'Mr. Yod',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'footballProduct.png',
            ],
            [
                'product_name' => 'Punchingbag',
                'slug' => 'punchingbag',
                'description' => 'Sturdy bag used for practicing punching and kicking techniques in martial arts or boxing',
                'price'=>'3300',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'leather',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'punchingbagProduct.png',
            ],
            [
                'product_name' => 'Jenga',
                'slug' => 'jenga',
                'description' => 'Jenga is a game of skill and balance where players remove blocks from a tower and stack them on top.',
                'price'=>'1200',
                'color'=>'red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'wood',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'jengaProduct.png',
            ],
            [
                'product_name' => 'Ludo',
                'slug' => 'ludo',
                'description' => 'Ludo is a board game where players race their tokens around the board to reach the finish line first.',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'wood',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'ludoProduct.png',
            ],
            [
                'product_name' => 'Poppet',
                'slug' => 'poppet',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'100',
                'color'=>'red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'poppetProduct.png',
            ],
            [
                'product_name' => 'Remote Control Car',
                'slug' => 'remote-control-car',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'1800',
                'color'=>'red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'remoteCarProduct.png',
            ],
            [
                'product_name' => 'Rubik Cube',
                'slug' => 'rubik-cube',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'120',
                'color'=>'red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'rubikCubeProduct.png',
            ],
            [
                'product_name' => 'UNO',
                'slug' => 'uno',
                'description' => 'Please change the description from the seeder if possible else change by editing',
                'price'=>'100',
                'color'=>'red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'unoProduct.png',
            ],
        ];
        product::insert($products);
    }
}
