<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products=[
            [
                'product_name' => 'Beauty Blender',
                'slug' => 'beautry-blender',
                'description' => 'The Beauty Blender, renowned for its latex-free composition, stands as a quintessential tool in the realm of makeup application. Its iconic egg-shaped design revolutionized the beauty industry, enabling seamless blending of various formulations, including liquid foundations, creamy concealers, and loose powders. Crafted with precision, this versatile sponge ensures flawless coverage and an airbrushed finish with minimal product wastage. Its ergonomic shape fits snugly into the contours of the face, facilitating effortless blending in hard-to-reach areas like the under eyes and around the nose. Moreover, the Beauty Blender\'s unique material composition guarantees a streak-free application, elevating the makeup experience for both professionals and enthusiasts alike. Unlike traditional makeup brushes, this innovative tool prevents product absorption, allowing for maximum pigment dispersion and optimal color payoff. Whether you\'re aiming for a natural, everyday look or a glamorous, full-coverage finish, the Beauty Blender effortlessly adapts to your desired makeup style. Beyond its functional benefits, the Beauty Blender embodies a philosophy of inclusivity and empowerment. With its ability to cater to a diverse range of skin types and tones, it celebrates individuality and encourages self-expression. From makeup novices experimenting with their first foundation to seasoned artists creating masterful looks, the Beauty Blender fosters creativity and confidence in every application. Furthermore, the Beauty Blender\'s commitment to sustainability underscores its appeal to conscientious consumers. Manufactured with eco-friendly materials and packaged in recyclable materials, it embodies a dedication to environmental stewardship. By prioritizing sustainability without compromising performance, the Beauty Blender sets a new standard for ethical beauty practices in the industry. In essence, the Beauty Blender transcends its status as a mere makeup tool; it represents a symbol of innovation, inclusivity, and sustainability in the beauty landscape. With its unparalleled blending capabilities, ergonomic design, and commitment to ethical practices, it continues to shape the way we approach makeup application, empowering individuals to unleash their creativity and embrace their unique beauty with confidence.',
                'price'=>'100',
                'color'=>'multicolor',
                'category_id'=>'1',
                'size'=>'L',
                'material'=>'Sponge',
                'brand'=> 'None',
                'weight'=>'0.3',
                'warranty'=>'0',
                'merchant_id'=>'2',
                'images'=>'beautyblenderProduct.png',
            ],
            [
                'product_name' => 'Body Oil',
                'slug' => 'baby-oil',
                'description' => 'Indulge your skin in the luxurious embrace of nature with our moisturizing skincare product crafted from the finest natural oils, including the nourishing essence of coconut. Our formula is delicately designed to provide intense hydration, leaving your skin irresistibly smooth, soft, and radiant.',
                'price'=>'1100',
                'color'=>'None',
                'category_id'=>'1',
                'size'=>'XL',
                'material'=>'Coconut',
                'brand'=> 'Aveeno',
                'weight'=>'0.5',
                'warranty'=>'',
                'merchant_id'=>'3',
                'images'=>'bodyOilProduct.png',
            ],
            [
                'product_name' => 'Eyelash Curler',
                'slug' => 'eyelash-curler',
                'description' => 'Beauty tool used to curl lashes for an enhanced, wide-eyed look, typically featuring a curved design to fit the shape of the eye and a handle for easy use.With its ergonomic design and gentle silicone pads, this curler fits the eye shape perfectly, providing comfortable control for beautifully curled lashes. Enhance your look with ease using the Revlon Eyelash Curler.',
                'price'=>'500',
                'color'=>'black',
                'category_id'=>'1',
                'size'=>'None',
                'material'=>'Metal',
                'brand'=> 'Revlon',
                'weight'=>'0.3',
                'warranty'=>'1',
                'merchant_id'=>'4',
                'images'=>'eyeLashCurlerProduct.png',
            ],
            [
                'product_name' => 'Hair Brush',
                'slug' => 'hair-brush',
                'description' => 'Velvet, soft-touch handle for a comfortable hold, Compact size, perfect for travel, Hypoallergenic, Ball-tipped bristles will not snag or pull hair, Cushion base for effortless styling. Elevate your hair care routine with the ultimate blend of comfort, convenience, and performance.',
                'price'=>'700',
                'color'=>'White',
                'category_id'=>'1',
                'size'=>'None',
                'material'=>'plastic',
                'brand'=> 'Conair',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'hairbrushProduct.png',
            ],
            [
                'product_name' => 'Lipstick',
                'slug' => 'lipstick',
                'description' => ' Iconic lipstick by Chanel With vibrant hue and luxurious formula, it delivers intense color and a smooth finish. Long-lasting wear ensures your lips remain flawless, while its sleek packaging adds a touch of elegance to your makeup routine..',
                'price'=>'2000',
                'color'=>'Red',
                'category_id'=>'1',
                'size'=>'XL',
                'material'=>'wax',
                'brand'=> 'Chanel',
                'weight'=>'1',
                'warranty'=>'1',
                'merchant_id'=>'3',
                'images'=>'Lipstick.png',
            ],
            [
                'product_name' => 'Mascara',
                'slug' => 'mascara',
                'description' => 'Gucci mascara, designed to deliver both volumizing and lengthening effects. Its luxurious formula provides rich color and lasting wear, while the packaging adds a stylish touch to your makeup collection.',
                'price'=>'1600',
                'color'=>'Black',
                'category_id'=>'1',
                'size'=>'None',
                'material'=>'None',
                'brand'=> 'Gucci',
                'weight'=>'0.2',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'mascaraProduct.png',
            ],
            [
                'product_name' => 'Perfume',
                'slug' => 'perfume',
                'description' => 'Launched by the design house of Christian Dior. Bright and colorful, Miss Dior Absolutely Blooming is an extravagant floral fragrance you return to again and again. Delectable tangy Red Berry notes are embroidered on a fresh Peony accord. Exalted by a sublime duo of Grasse Rose and Damascus Rose, this infinite blooming of fresh flowers is comforted in a base of White Musk notes. A positive, cheery olfactory harmony for a mischievous and irresistible Miss Dior.',
                'price'=>'3000',
                'color'=>'Pink',
                'category_id'=>'1',
                'size'=>'None',
                'material'=>'None',
                'brand'=> 'Dior',
                'weight'=>'1',
                'warranty'=>'0',
                'merchant_id'=>'2',
                'images'=>'perfumeProduct.png',
            ],
            [
                'product_name' => 'Kite Runner',
                'slug' => 'kite-runner',
                'description' => '"The Kite Runner" by Khaled Hosseini follows Amir, a boy from Kabul, Afghanistan, as he grapples with friendship, guilt, and redemption amid the backdrop of his country\'s turbulent history.The unforgettable, heartbreaking story of the unlikely friendship between a wealthy boy and the son of his father’s servant, caught in the tragic sweep of history, The Kite Runner transports readers to Afghanistan at a tense and crucial moment of change and destruction. A powerful story of friendship, it is also about the power of reading, the price of betrayal, and the possibility of redemption; and an exploration of the power of fathers over sons—their love, their sacrifices, their lies.',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'7',
                'size'=>'XL',
                'material'=>'paper',
                'brand'=> 'None',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'kiterunnerProduct.png',
            ],
            [
                'product_name' => 'Notebook',
                'slug' => 'notebook',
                'description' => 'The Mead Spiral 1 Subject Notebook is really versatile and perfect for different uses like class assignments or homework. It\'s great for one subject, making it super handy for your favorite class or any project. It has 70 wide ruled sheets, so you have plenty of space for notes. The wide ruling is perfect for younger students who need more space between lines. Each sheet measures 10-1/2" x 7-1/2" when torn out, with an overall size of 10-1/2" x 8". It\'s easy to tear out thanks to the perforation, leaving clean edges. Plus, it\'s 3-hole punched so you can store it in your binder. The covers are coated for durability, and it\'s great for color coding by subject. You get a pack of 24 notebooks, each crafted with pride and assembled with care.',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'7',
                'size'=>'XL',
                'material'=>'paper',
                'brand'=> 'Classmate',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'notebookProduct.png',
            ],
            [
                'product_name' => 'Painting Color',
                'slug' => 'panting-color',
                'description' => 'The set includes 24 large tubes of high-quality acrylic paint in vivid colors, each containing 18ml of paint. With a total of 72 unique and eye-catching colors, these water-based acrylic paints allow you to create stunning artworks. They are superior in performance and will truly bring your creations to life. Perfect for both professional artists and young beginners alike, these art supplies will inspire and enhance your artistic endeavors..',
                'price'=>'900',
                'color'=>'multicolor',
                'category_id'=>'7',
                'size'=>'XL',
                'paint type'=>'Arcylic',
                'brand'=> 'TMOL',
                'weight'=>'0.5',
                'warranty'=>'0',
                'merchant_id'=>'2',
                'images'=>'paintingColorProduct.png',
            ],
            [
                'product_name' => 'Pilot pen',
                'slug' => 'pilot-pen',
                'description' => 'The G2 pen writes smoothly because of its gel ink and lasts a long time. It\'s easy to hold with its comfortable rubber grip, making it great for long writing sessions. You can use it for everyday tasks like writing notes or making lists, and its quick-drying ink helps prevent smudges. Plus, you can refill it instead of throwing it away, which saves money and reduces waste.',
                'price'=>'400',
                'ink color'=>'Black',
                'category_id'=>'7',
                'size'=>'0.7mm',
                'material'=>'plastic',
                'brand'=> 'PILOT',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'pilotpenProduct.png',
            ],
            [
                'product_name' => 'Sketching Marker',
                'slug' => 'sketching-marker',
                'description' => 'The Sakura Pigma Micron is a fine-tip pen with special ink that dries fast and won\'t smudge, fade, or wash away with water. It\'s perfect for drawing and adding details to sketches, especially when combined with watercolors. Whether you\'re working on technical drawings or artistic illustrations, this pen is designed for both. Its ink won\'t bleed through paper and is permanent, making it great for tracing as well.',
                'price'=>'1200',
                'color'=>'BLACK',
                'category_id'=>'7',
                'size'=>'0.7mm',
                'material'=>'plastic',
                'brand'=> 'SAKURA',
                'weight'=>'0.2',
                'warranty'=>'0',
                'merchant_id'=>'4',
                'images'=>'sketchingMarkerProduct.png',
            ],
            [
                'product_name' => 'Airpods',
                'slug' => 'airpods',
                'description' => '
                Apple AirPods are wireless earbuds that offer high-quality audio and seamless connectivity to Apple devices. They feature a sleek design, effortless setup, and intuitive touch controls. With a compact charging case that provides additional power on the go, AirPods deliver a truly wireless listening experience for music, calls, and more.',
                'price'=>'30000',
                'color'=>'white',
                'category_id'=>'2',
                'size'=>'None',
                'material'=>'plastic',
                'brand'=> 'Apple',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'airpodsProduct.png',
            ],
            [
                'product_name' => 'Canon Camera',
                'slug' => 'canon-camera',
                'description' => 'Creating distinctive stories with DSLR quality photos and Full HD movies is easier than you think with the 18 Megapixel Canon EOS Rebel T100. Share instantly and shoot remotely via your compatible smartphone with Wi-Fi and the Canon Camera Connect app. The powerful 18 Megapixel sensor has up to 19 times more surface area than many smartphones, and you can instantly transfer photos and movies to your smart device. The Canon EOS Rebel T100 has a Scene Intelligent Auto feature that allows you to simply frame and shoot for great results. It also features Guided Live View shooting with Creative Auto mode, and you can add unique finishes with Creative Filters. The Canon EOS Rebel T100 makes it fast and easy to share all the moments that matter.',
                'price'=>'90000',
                'color'=>'Black',
                'category_id'=>'2',
                'size'=>'none',
                'material'=>'metal',
                'brand'=> 'canon',
                'weight'=>'1',
                'warranty'=>'5',
                'merchant_id'=>'3',
                'images'=>'CanonProduct.png',
            ],
            [
                'product_name' => 'Headphone',
                'slug' => 'headphone',
                'description' => 'Apple headphones are premium-quality audio accessories designed for seamless integration with Apple devices. They offer excellent sound performance, comfortable fit, and intuitive controls. With sleek designs and advanced technology, Apple headphones deliver an exceptional listening experience for music, calls, and more.',
                'price'=>'80000',
                'color'=>'Silver',
                'category_id'=>'2',
                'size'=>'None',
                'material'=>'plastic',
                'brand'=> 'Apple',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'headphoneProduct.png',
            ],
            [
                'product_name' => 'Iphone11 Charger',
                'slug' => 'iphone11-charger',
                'description' => 'The iPhone charger is a compact and efficient accessory designed specifically for charging Apple devices. It features a durable construction and rapid charging capabilities, ensuring quick and reliable power whenever you need it. With its sleek design and convenient portability, the iPhone charger is an essential accessory for keeping your devices powered up on the go.',
                'price'=>'2000',
                'color'=>'white',
                'category_id'=>'2',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'Apple',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'iphone11ChargerProduct.png',
            ],
            [
                'product_name' => 'Mac Book Pro M2',
                'slug' => 'mac-book-pro-m2',
                'description' => 'The new MacBook Pro, powered by the M2 Pro chip, offers unparalleled performance and efficiency. It boasts a longer battery life and stunning Liquid Retina XDR display. With up to a 10-core CPU, 16-core GPU, and 32GB unified memory, it delivers lightning-fast speed and fluid multitasking. The M2 Pro chip is designed with over 40 billion transistors for even greater performance compared to previous models. With improved CPU and GPU cores, it ensures smooth running of professional applications. Overall, the MacBook Pro with M2 Pro chip takes pro-level performance to new heights.',
                'price'=>'150000',
                'color'=>'space grey',
                'category_id'=>'2',
                'size'=>'14 inches',
                'material'=>'metal',
                'brand'=> 'Apple',
                'weight'=>'2',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'macBookProM2Product.png',
            ],
            [
                'product_name' => 'Power bank',
                'slug' => 'power-bank',
                'description' => '
                This power bank has a huge capacity of 50000mAh, which means it can charge your devices multiple times before needing to be recharged itself. It\'s compatible with various devices like smartphones, tablets, and even heated clothing items. With four USB outputs, you can charge up to four devices simultaneously. Plus, it offers fast charging with its USB-A port, delivering charging speeds twice as fast as regular chargers. Additionally, it features both micro and USB-C inputs, allowing for quick recharging of the power bank itself.',
                'price'=>'3000',
                'color'=>'Black',
                'category_id'=>'2',
                'Battery Capacity'=>'50000 maAh',
                'material'=>'metal',
                'brand'=> 'VINCOSY',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'powerbankProduct.png',
            ],
            [
                'product_name' => 'Jacket',
                'slug' => 'jacket',
                'description' => 'The stylish combination of a classic denim jacket and a cozy hoodie creates a fashionable yet practical piece of clothing that offers versatile layering options for a variety of casual and urban looks. This unique hybrid design seamlessly blends the timeless appeal of denim with the comfort and warmth of a hoodie, making it suitable for a wide range of occasions and settings. Whether you\'re running errands in the city or meeting friends for a weekend brunch, this jacket offers both style and functionality, effortlessly elevating your outfit while keeping you comfortable and on-trend.',
                'price'=>'1700',
                'color'=>'Light blue',
                'category_id'=>'3',
                'size'=>'XL',
                'material'=>'Denim Cotton',
                'brand'=> 'No brand',
                'weight'=>'1',
                'warranty'=>'0',
                'merchant_id'=>'2',
                'images'=>'jacket.png',
            ],
            [
                'product_name' => 'Pant',
                'slug' => 'pant',
                'description' => 'These denim pants combine the timeless style of jeans with the practicality of cargo pants, featuring multiple pockets for convenient storage. Perfect for various activities, they offer functionality without compromising on style. Whether you\'re running errands or enjoying outdoor adventures, these pants provide ample space to keep your essentials close at hand. With their durable denim fabric and versatile design, they\'re a stylish and functional choice for any casual occasion.',
                'price'=>'1800',
                'color'=>'Dark Blue',
                'category_id'=>'3',
                'size'=>'L',
                'material'=>'Denim',
                'brand'=> 'No brand',
                'weight'=>'0.7',
                'warranty'=>'0',
                'merchant_id'=>'3',
                'images'=>'pantProduct.png',
            ],
            [
                'product_name' => 'Sari',
                'slug' => 'sari',
                'description' => 'This elegant traditional sari, crafted from luxurious Banarasi silk, features intricate woven designs and motifs in shades of green, making it perfect for special occasions and cultural celebrations. It exudes timeless sophistication and captures the rich heritage of Indian craftsmanship. Whether worn for weddings, festivals, or other significant events, this sari adds an element of grace and elegance to any attire, showcasing the wearer\'s appreciation for traditional aesthetics and fine craftsmanship.',
                'price'=>'7000',
                'color'=>'Green',
                'category_id'=>'3',
                'size'=>'XL',
                'material'=>'Banarasi',
                'brand'=> 'No brand',
                'weight'=>'1',
                'warranty'=>'0',
                'merchant_id'=>'4',
                'images'=>'sariProduct.png',
            ],
            [
                'product_name' => 'Sweater',
                'slug' => 'sweater',
                'description' => ' 
                This classic knitwear garment, crafted from warm wool in a timeless black color, is not only practical for colder weather but also effortlessly stylish. Its versatility allows for easy layering, making it a go-to choice for adding sophistication to any outfit. Whether paired with jeans for a casual look or worn over a dress for a more formal occasion, this knitwear piece adds an extra layer of warmth and elegance. Its classic design ensures it never goes out of style, making it a staple in any wardrobe for years to come.',
                'price'=>'1900',
                'color'=>'Black',
                'category_id'=>'3',
                'size'=>'Sm',
                'material'=>'Woolen',
                'brand'=> 'Mode23',
                'weight'=>'1',
                'warranty'=>'0',
                'merchant_id'=>'2',
                'images'=>'sweater.png',
            ],
            [
                'product_name' => 'Tshirt',
                'slug' => 'tshirt',
                'description' => 'This iconic band merchandise showcases the Guns N\' Roses logo and artwork, capturing the essence of the legendary rock band. Crafted from comfortable cotton fabric, it offers fans a stylish and cozy way to show their love for their favorite music group. Whether worn to concerts, casual outings, or simply as a statement piece, this merchandise is a must-have for any die-hard fan. With its bold design and high-quality materials, it\'s the perfect addition to any rock enthusiast\'s collection.',
                'price'=>'900',
                'color'=>'Black',
                'category_id'=>'3',
                'size'=>'L',
                'material'=>'cotton',
                'brand'=> 'No brand',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'tshirtProduct.png',
            ],
            [
                'product_name' => 'Coffee',
                'slug' => 'coffee',
                'description' => 'This coffee blend may seem simple at first glance, but it\'s a carefully crafted combination of fine Latin American beans. Roasted to a dark chestnut color, it glistens with richness and depth. Each sip is a symphony of flavor, with notes of nut and cocoa perfectly balanced, complemented by a subtle sweetness from the roast. ',
                'price'=>'2500',
                'color'=>'None',
                'category_id'=>'4',
                'size'=>'L',
                'material'=>'Whole bean',
                'brand'=> 'Starbucks',
                'weight'=>'0.7',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'coffeeProduct.png',
            ],
            [
                'product_name' => 'Corn Flakes',
                'slug' => 'con-flakes',
                'description' => '
                Kellogg\'s Corn Flakes cereal offers a nourishing and wholesome breakfast option that stands out for its quality. Made from real natural corn and fortified with iron and eight essential vitamins, it delivers a balanced combination of nutrients along with the original flavor of corn. Enjoy a delicious and fulfilling start to your day with Kellogg\'s Corn Flakes.',
                'price'=>'700',
                'color'=>'None',
                'category_id'=>'4',
                'size'=>'XL',
                'material'=>'corn',
                'brand'=> 'Kelloggs',
                'weight'=>'0.9',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'cornFlakesProduct.png',
            ],
            [
                'product_name' => 'Egg',
                'slug' => 'egg',
                'description' => 'A dozen fresh eggs, laid by chickens, serve as a versatile ingredient in both cooking and baking. Rich in protein and nutrients, they are essential for a wide range of recipes and dishes, adding texture, flavor, and nutritional value. Whether used to make fluffy omelets, moist cakes, or savory quiches, eggs are a staple in the kitchen, contributing to the deliciousness and wholesomeness of many culinary creations.',
                'price'=>'700',
                'color'=>'None',
                'category_id'=>'4',
                'size'=>'XL',
                'material'=>'None',
                'brand'=> 'None',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'eggProduct.png',
            ],
            [
                'product_name' => 'Juice',
                'slug' => 'juice',
                'description' => 'This nutrient-rich beverage is crafted from fresh carrots, offering a wealth of vitamins, minerals, and antioxidants. It promotes overall health and wellness with its nourishing properties, while its refreshing taste adds to the enjoyment of consuming it. With each sip, you\'re not only treating your taste buds but also nourishing your body with essential nutrients that support your well-being.',
                'price'=>'300',
                'color'=>'Orange',
                'category_id'=>'4',
                'size'=>'L',
                'material'=>'carrot',
                'brand'=> 'None',
                'weight'=>'1',
                'warranty'=>'1',
                'merchant_id'=>'4',
                'images'=>'juiceProduct.png',
            ],
            [
                'product_name' => 'Milk',
                'slug' => 'milk',
                'description' => 'Dairy-free alternative made from almonds, offering a creamy texture and nutty flavor, suitable for vegans and those with lactose intolerance, enriched with vitamins and minerals for a nutritious beverage option.',
                'price'=>'400',
                'color'=>'None',
                'category_id'=>'4',
                'size'=>'L',
                'material'=>'Almond',
                'brand'=> 'Silk',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'milkProduct.png',
            ],
            [
                'product_name' => 'Sausage',
                'slug' => 'sausage',
                'description' => 'Savory meat product typically made from ground meat mixed with herbs, spices, and seasonings, often encased in a casing, and cooked by grilling, frying, or baking, popular in various cuisines worldwide.',
                'price'=>'520',
                'color'=>'None',
                'category_id'=>'4',
                'size'=>'small',
                'material'=>'Chicken',
                'brand'=> 'None',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'sausageProduct.png',
            ],
            [
                'product_name' => 'Bookcase',
                'slug' => 'bookcase',
                'description' => 'This stylish bookcase is designed to elevate the elegance of any room while providing practical storage solutions. Featuring adjustable shelves, it offers versatility to accommodate various items of different sizes. With ample storage space, this bookcase is perfect for displaying books, decorative pieces, and other belongings, helping to keep the space organized and tidy. Its sleek design adds a touch of sophistication to any decor, making it a functional and stylish addition to your home or office.',
                'price'=>'320',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'metal',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'bookcaseProduct.png',
            ],
            [
                'product_name' => 'Chair',
                'slug' => 'chair',
                'description' => '
                This chair combines modern design with ergonomic support, making it ideal for both work and relaxation. Its sleek and contemporary appearance adds a stylish touch to any space, while its ergonomic features ensure comfort and proper posture whether you\'re working at a desk or simply unwinding. With its versatile functionality, this chair seamlessly transitions between work and leisure, providing comfort and support throughout the day.',
                'price'=>'1400',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'wooden',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'chair.png',
            ],
            [
                'product_name' => 'Clock',
                'slug' => 'clock',
                'description' => '
                A classic style clock is a timeless timekeeping device, available in either mechanical or electrical form. It elegantly displays the passage of time, serving as a functional and decorative piece in any space. Whether it\'s a traditional pendulum clock or a sleek digital display, a classic clock adds a touch of sophistication to any room while fulfilling its primary purpose of keeping time.',
                'price'=>'850',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'clockProduct.png',
            ],
            [
                'product_name' => 'Couch',
                'slug' => 'couch',
                'description' => 'This stylish couch provides luxurious comfort, making it the perfect centerpiece for any living space. With its plush cushions and inviting design, it creates a cozy atmosphere where you can relax and unwind after a long day. Its sleek and modern appearance adds a touch of sophistication to your home decor, while its comfortable seating ensures that you and your guests can lounge in style. Whether you\'re watching TV, reading a book, or simply enjoying some downtime, this couch offers the perfect blend of style and comfort for your home.',
                'price'=>'3200',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'couchProduct.png',
            ],
            [
                'product_name' => 'Knife',
                'slug' => 'knife',
                'description' => 'This sleek knife is expertly crafted to deliver precision and durability, making it an essential tool for any kitchen or outdoor adventure. Its sharp blade ensures effortless cutting, while its sturdy construction guarantees long-lasting performance in various tasks. Whether you\'re preparing ingredients in the kitchen or tackling outdoor challenges, this knife is designed to meet your needs with reliability and style.',
                'price'=>'150',
                'color'=>'red',
                'category_id'=>'5',
                'size'=>'XL',
                'material'=>'Steel',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'Knife.png',
            ],
            [
                'product_name' => 'Badminton',
                'slug' => 'badminton',
                'description' => '
                This shuttlecock is designed to facilitate fast rallies and precise shots, ensuring an exhilarating game for players of all skill levels. Its aerodynamic design enables swift movement through the air, allowing for quick and dynamic gameplay. Whether you\'re a beginner or an experienced player, this shuttlecock enhances the excitement of every match, providing the perfect balance of speed and accuracy for an enjoyable badminton experience.',
                'price'=>'550',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'plastic',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'badmintonProduct.png',
            ],
            [
                'product_name' => 'Basketball',
                'slug' => 'basketball',
                'description' => 'This product is specifically engineered for durability and optimal bounce, making it perfect for both practice sessions and intense games alike. Whether you\'re honing your skills on the practice court or engaged in a high-stakes match, this item ensures consistent performance and reliability. Its robust construction withstands repeated use, guaranteeing longevity and maintaining its bounce over time. ',
                'price'=>'800',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'rubber',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'basketballProduct.png',
            ],
            [
                'product_name' => 'Boxing Gloves',
                'slug' => 'boxing-gloves',
                'description' => '
                These durable boxing gloves are crafted from high-quality materials, ensuring long-lasting performance and protection. Designed to withstand rigorous training sessions and bouts, they provide reliable support and cushioning to safeguard your hands and wrists. With their superior construction and attention to detail, these gloves offer peace of mind, allowing you to focus on your training or competition without worrying about equipment failure. ',
                'price'=>'5500',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'leather',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'boxingGlovesProduct.png',
            ],
            [
                'product_name' => 'Dumbell',
                'slug' => 'dumbell',
                'description' => 'Dumbbells consist of short bars with weighted ends, making them versatile tools for strength training and muscle toning exercises. They are commonly used in a wide range of workouts, from traditional weightlifting routines to more dynamic movements like lunges, curls, and shoulder presses. Dumbbells offer a convenient way to target specific muscle groups and can be adjusted to suit varying fitness levels and goals.',
                'price'=>'1400',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'metal',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'dumbellProduct.png',
            ],
            [
                'product_name' => 'Football',
                'slug' => 'football',
                'description' => 'This football is crafted for durability and optimal performance, ideal for practice sessions and intense games.',
                'price'=>'700',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'leather',
                'brand'=> 'Mr. Yod',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'footballProduct.png',
            ],
            [
                'product_name' => 'Punchingbag',
                'slug' => 'punchingbag',
                'description' => 'A punching bag is a robust and durable bag specifically designed for practicing punching and kicking techniques in martial arts or boxing. It\'s commonly used by athletes and enthusiasts alike to improve striking skills, speed, and accuracy while also providing an excellent cardiovascular workout.',
                'price'=>'3300',
                'color'=>'red',
                'category_id'=>'6',
                'size'=>'XL',
                'material'=>'leather',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'2',
                'images'=>'punchingbagProduct.png',
            ],
            [
                'product_name' => 'Jenga',
                'slug' => 'jenga',
                'description' => '
                Jenga is a captivating game that demands both skill and precision, captivating players as they meticulously remove blocks from a tower and delicately balance them atop the ever-growing structure. With each move, participants must carefully strategize and adapt to maintain stability, all while anticipating the tower\'s impending collapse.',
                'price'=>'1200',
                'color'=>'red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'wood',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'3',
                'images'=>'jengaProduct.png',
            ],
            [
                'product_name' => 'Ludo',
                'slug' => 'ludo',
                'description' => 'Ludo is an exciting board game where players embark on a thrilling race with their tokens, maneuvering them strategically around the board in a quest to be the first to reach the finish line. With each roll of the dice, players navigate their tokens through a series of obstacles and challenges, aiming to outmaneuver their opponents while also thwarting their progress. ',
                'price'=>'1000',
                'color'=>'red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'wood',
                'brand'=> 'local',
                'weight'=>'1',
                'warranty'=>'2',
                'merchant_id'=>'4',
                'images'=>'ludoProduct.png',
            ],
            [
                'product_name' => 'Poppet',
                'slug' => 'poppet',
                'description' => 'When pressed, the bubble will emit a subtle popping sound, adding to the satisfying sensory experience.',
                'price'=>'300',
                'color'=>'Yellow',
                'category_id'=>'8',
                'size'=>'None',
                'material'=>'Plastic',
                'brand'=> 'No brand',
                'weight'=>'0.1',
                'warranty'=>'0',
                'merchant_id'=>'2',
                'images'=>'poppetProduct.png',
            ],
            [
                'product_name' => 'Remote Control Car',
                'slug' => 'remote-control-car',
                'description' => ' Miniature vehicle controlled wirelessly. Drive forward, backward, left, and right. Enjoy fast-paced fun indoors or outdoors.Experience the thrill of controlling a miniature vehicle wirelessly, with the ability to drive forward, backward, left, and right. This versatile remote-controlled car provides fast-paced excitement for both indoor and outdoor play. ',
                'price'=>'1200',
                'color'=>'Red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'Plastic',
                'brand'=> 'No brand',
                'weight'=>'0.4',
                'warranty'=>'1',
                'merchant_id'=>'3',
                'images'=>'remoteCarProduct.png',
            ],
            [
                'product_name' => 'Rubik Cube',
                'slug' => 'rubik-cube',
                'description' => 'The Rubik\'s Cube is a renowned 3D combination puzzle featuring colored squares on each side. The challenge is to align these squares back to their original positions by twisting and turning the cube. It offers a stimulating mental exercise that tests problem-solving skills, spatial reasoning, and patience, providing hours of entertainment and satisfaction for players of all levels.',
                'price'=>'150',
                'color'=>'Red',
                'category_id'=>'8',
                'size'=>'XL',
                'material'=>'Plastic',
                'brand'=> 'No brand',
                'weight'=>'0.4',
                'warranty'=>'1',
                'merchant_id'=>'4',
                'images'=>'rubikCubeProduct.png',
            ],
            [
                'product_name' => 'UNO',
                'slug' => 'uno',
                'description' => 'UNO is a popular card game that offers fast-paced and exciting gameplay for players of all ages. The objective is to be the first to empty your hand of cards by matching them with the top card of the discard pile based on either color, number, or symbol. With special action cards like Skip, Reverse, and Draw Two adding twists and turns to the game, UNO keeps players on their toes and provides endless fun for family and friends alike.',
                'price'=>'250',
                'color'=>'Multicolor',
                'category_id'=>'8',
                'size'=>'None',
                'material'=>'Paper',
                'brand'=> 'Mattel Games',
                'weight'=>'0.1',
                'warranty'=>'0',
                'merchant_id'=>'2',
                'images'=>'unoProduct.png',
            ],
        ];
        product::insert($products);
    }
}
