<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products=[
            [
                'product_name' => 'Tshirt',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Clothes',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-1.png',
            ],
            [
                'product_name' => 'Pant',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Stationary',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-2.png',
            ],
            [
                'product_name' => 'Jacket',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Daily Use',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-3.png',
            ],
            [
                'product_name' => 'Tshirt',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Vegetables',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-4.png',
            ],
            [
                'product_name' => 'Pant',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Vegetables',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-5.png',
            ],
            [
                'product_name' => 'Jacket',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Daily Use',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-6.png',
            ],
            [
                'product_name' => 'Tshirt',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Stationary',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-7.png',
            ],
            [
                'product_name' => 'Pant',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Clothes',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-8.png',
            ],
            [
                'product_name' => 'Jacket',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Vegetables',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-9.png',
            ],
            [
                'product_name' => 'Tshirt',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Daily Use',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-10.png',
            ],
            [
                'product_name' => 'Pant',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Stationary',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-11.png',
            ],
            [
                'product_name' => 'Jacket',
                'price'=>'1000',
                'color'=>'red',
                'category'=>'Vegetables',
                'size'=>'XL',
                'material'=>'cotton',
                'brand'=> 'Nike',
                'weight'=>'1',
                'warranty'=>'2',
                'shop_name'=>'merchant',
                'shop_address'=>'',
                'merchant_email'=>'merchant@gmail.com',
                'images'=>'product-12.png',
            ],
        ];
        product::insert($products);
    }
}
