@include('backend.ajax.search')
@include('backend.ajax.add_to_cart')
@if(request()->segment(1)==="admin" && request()->segment(2)==="categories")
    @include('backend.ajax.category')
@elseif (\Route::current()->getName() == 'admin.merchant.new')
    @include('backend.ajax.merchant')
@elseif (\Route::current()->getName() == 'admin.merchant.verify')
    @include('backend.ajax.merchant')
@elseif(\Route::current()->getName() == 'admin.customer.list')
    @include('backend.ajax.customer')
@elseif(request()->is('admin/order*'))
    @include('backend.ajax.address')
@elseif(\Route::current()->getName() == 'merchant.product')
    @include('backend.ajax.product')
@endif